export const inventory = [
  {
    id: 1,
    name: "Wireless Mouse",
    category: "Electronics",
    quantity: 45,
    price: 15.99,
    sku: "ELEC-001",
    inStock: true,
    lastUpdated: "2025-09-20",
  },
  {
    id: 2,
    name: "Gaming Keyboard",
    category: "Electronics",
    quantity: 20,
    price: 39.99,
    sku: "ELEC-002",
    inStock: true,
    lastUpdated: "2025-09-21",
  },
  {
    id: 3,
    name: "Office Chair",
    category: "Furniture",
    quantity: 12,
    price: 129.99,
    sku: "FURN-001",
    inStock: true,
    lastUpdated: "2025-09-19",
  },
  {
    id: 4,
    name: "Notebook (A4)",
    category: "Stationery",
    quantity: 100,
    price: 2.5,
    sku: "STAT-001",
    inStock: true,
    lastUpdated: "2025-09-18",
  },
  {
    id: 5,
    name: "Ballpoint Pen",
    category: "Stationery",
    quantity: 200,
    price: 0.99,
    sku: "STAT-002",
    inStock: true,
    lastUpdated: "2025-09-22",
  },
  {
    id: 6,
    name: "LED Desk Lamp",
    category: "Electronics",
    quantity: 8,
    price: 25.0,
    sku: "ELEC-003",
    inStock: true,
    lastUpdated: "2025-09-15",
  },
  {
    id: 7,
    name: "USB Flash Drive 32GB",
    category: "Electronics",
    quantity: 60,
    price: 9.5,
    sku: "ELEC-004",
    inStock: true,
    lastUpdated: "2025-09-20",
  },
  {
    id: 8,
    name: "Coffee Mug",
    category: "Kitchen",
    quantity: 30,
    price: 4.99,
    sku: "KITCH-001",
    inStock: true,
    lastUpdated: "2025-09-14",
  },
  {
    id: 9,
    name: "Filing Cabinet",
    category: "Furniture",
    quantity: 5,
    price: 210.0,
    sku: "FURN-002",
    inStock: true,
    lastUpdated: "2025-09-17",
  },
  {
    id: 10,
    name: "Sticky Notes",
    category: "Stationery",
    quantity: 150,
    price: 1.5,
    sku: "STAT-003",
    inStock: true,
    lastUpdated: "2025-09-19",
  },
  {
    id: 11,
    name: "HDMI Cable 2m",
    category: "Electronics",
    quantity: 75,
    price: 7.99,
    sku: "ELEC-005",
    inStock: true,
    lastUpdated: "2025-09-23",
  },
  {
    id: 12,
    name: "Monitor Stand",
    category: "Furniture",
    quantity: 18,
    price: 35.0,
    sku: "FURN-003",
    inStock: true,
    lastUpdated: "2025-09-22",
  },
  {
    id: 13,
    name: "Paper Clips (100 pack)",
    category: "Stationery",
    quantity: 250,
    price: 1.2,
    sku: "STAT-004",
    inStock: true,
    lastUpdated: "2025-09-18",
  },
  {
    id: 14,
    name: "Ergonomic Mouse Pad",
    category: "Electronics",
    quantity: 40,
    price: 8.5,
    sku: "ELEC-006",
    inStock: true,
    lastUpdated: "2025-09-16",
  },
  {
    id: 15,
    name: "Desk Organizer",
    category: "Furniture",
    quantity: 22,
    price: 19.99,
    sku: "FURN-004",
    inStock: true,
    lastUpdated: "2025-09-20",
  },
  {
    id: 16,
    name: "Printer Paper (500 sheets)",
    category: "Stationery",
    quantity: 90,
    price: 6.99,
    sku: "STAT-005",
    inStock: true,
    lastUpdated: "2025-09-21",
  },
  {
    id: 17,
    name: "Laptop Stand",
    category: "Electronics",
    quantity: 10,
    price: 29.99,
    sku: "ELEC-007",
    inStock: true,
    lastUpdated: "2025-09-23",
  },
  {
    id: 18,
    name: "Desk Plant",
    category: "Decor",
    quantity: 15,
    price: 12.99,
    sku: "DECO-001",
    inStock: true,
    lastUpdated: "2025-09-19",
  },
  {
    id: 19,
    name: "Whiteboard Markers (Set of 4)",
    category: "Stationery",
    quantity: 70,
    price: 3.99,
    sku: "STAT-006",
    inStock: true,
    lastUpdated: "2025-09-22",
  },
  {
    id: 20,
    name: "Power Strip 6-Socket",
    category: "Electronics",
    quantity: 25,
    price: 14.99,
    sku: "ELEC-008",
    inStock: true,
    lastUpdated: "2025-09-15",
  },
  {
    id: 21,
    name: "Storage Box",
    category: "Furniture",
    quantity: 35,
    price: 10.99,
    sku: "FURN-005",
    inStock: true,
    lastUpdated: "2025-09-18",
  },
  {
    id: 22,
    name: "Stapler",
    category: "Stationery",
    quantity: 50,
    price: 5.5,
    sku: "STAT-007",
    inStock: true,
    lastUpdated: "2025-09-21",
  },
  {
    id: 23,
    name: "Surge Protector",
    category: "Electronics",
    quantity: 12,
    price: 18.99,
    sku: "ELEC-009",
    inStock: true,
    lastUpdated: "2025-09-20",
  },
  {
    id: 24,
    name: "Pen Holder",
    category: "Furniture",
    quantity: 60,
    price: 4.0,
    sku: "FURN-006",
    inStock: true,
    lastUpdated: "2025-09-17",
  },
  {
    id: 25,
    name: "Bluetooth Speaker",
    category: "Electronics",
    quantity: 7,
    price: 49.99,
    sku: "ELEC-010",
    inStock: true,
    lastUpdated: "2025-09-23",
  },
  {
    id: 26,
    name: "Binder Clips (Set of 12)",
    category: "Stationery",
    quantity: 130,
    price: 2.0,
    sku: "STAT-008",
    inStock: true,
    lastUpdated: "2025-09-19",
  },
  {
    id: 27,
    name: "Desk Mat",
    category: "Furniture",
    quantity: 16,
    price: 17.5,
    sku: "FURN-007",
    inStock: true,
    lastUpdated: "2025-09-16",
  },
  {
    id: 28,
    name: "Extension Cord 3m",
    category: "Electronics",
    quantity: 30,
    price: 11.0,
    sku: "ELEC-011",
    inStock: true,
    lastUpdated: "2025-09-14",
  },
  {
    id: 29,
    name: "Letter Tray",
    category: "Furniture",
    quantity: 27,
    price: 8.75,
    sku: "FURN-008",
    inStock: true,
    lastUpdated: "2025-09-15",
  },
  {
    id: 30,
    name: "Glue Stick",
    category: "Stationery",
    quantity: 85,
    price: 1.3,
    sku: "STAT-009",
    inStock: true,
    lastUpdated: "2025-09-20",
  },
];

export const fruits = [
  "Apple",
  "Banana",
  "Orange",
  "Mango",
  "Pineapple",
  "Grapes",
  "Watermelon",
  "Strawberry",
  "Blueberry",
  "Peach",
  "Cherry",
  "Papaya",
  "Guava",
  "Kiwi",
  "Pomegranate",
  "Lychee",
  "Dragonfruit",
  "Cantaloupe",
  "Plum",
  "Pear",
];

export const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 28,
    country: "USA",
    isActive: true,
  },
  {
    id: 2,
    name: "Sarah Khan",
    email: "sarah.khan@example.com",
    age: 24,
    country: "Pakistan",
    isActive: false,
  },
  {
    id: 3,
    name: "Liam Smith",
    email: "liam.smith@example.com",
    age: 31,
    country: "UK",
    isActive: true,
  },
  {
    id: 4,
    name: "Ava Lee",
    email: "ava.lee@example.com",
    age: 29,
    country: "Singapore",
    isActive: true,
  },
  {
    id: 5,
    name: "Ethan Brown",
    email: "ethan.brown@example.com",
    age: 35,
    country: "Canada",
    isActive: false,
  },
  {
    id: 6,
    name: "Mia Wong",
    email: "mia.wong@example.com",
    age: 27,
    country: "China",
    isActive: true,
  },
  {
    id: 7,
    name: "Noah Patel",
    email: "noah.patel@example.com",
    age: 22,
    country: "India",
    isActive: true,
  },
  {
    id: 8,
    name: "Isabella Garcia",
    email: "isabella.garcia@example.com",
    age: 30,
    country: "Mexico",
    isActive: false,
  },
  {
    id: 9,
    name: "Lucas Silva",
    email: "lucas.silva@example.com",
    age: 33,
    country: "Brazil",
    isActive: true,
  },
  {
    id: 10,
    name: "Sofia Rossi",
    email: "sofia.rossi@example.com",
    age: 26,
    country: "Italy",
    isActive: true,
  },
];
