export const fruits = [
  "Apple",
  "Banana",
  "Orange",
  "Mango",
  "Pineapple",
  "Grapes",
  "Watermelon",
  "Strawberry",
  "Blueberry",
  "Peach",
  "Cherry",
  "Papaya",
  "Guava",
  "Kiwi",
  "Pomegranate",
  "Lychee",
  "Dragonfruit",
  "Cantaloupe",
  "Plum",
  "Pear",
];

export const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    age: 28,
    country: "USA",
    isActive: true,
  },
  {
    id: 2,
    name: "Sarah Khan",
    email: "sarah.khan@example.com",
    age: 24,
    country: "Pakistan",
    isActive: false,
  },
  {
    id: 3,
    name: "Liam Smith",
    email: "liam.smith@example.com",
    age: 31,
    country: "UK",
    isActive: true,
  },
  {
    id: 4,
    name: "Ava Lee",
    email: "ava.lee@example.com",
    age: 29,
    country: "Singapore",
    isActive: true,
  },
  {
    id: 5,
    name: "Ethan Brown",
    email: "ethan.brown@example.com",
    age: 35,
    country: "Canada",
    isActive: false,
  },
  {
    id: 6,
    name: "Mia Wong",
    email: "mia.wong@example.com",
    age: 27,
    country: "China",
    isActive: true,
  },
  {
    id: 7,
    name: "Noah Patel",
    email: "noah.patel@example.com",
    age: 22,
    country: "India",
    isActive: true,
  },
  {
    id: 8,
    name: "Isabella Garcia",
    email: "isabella.garcia@example.com",
    age: 30,
    country: "Mexico",
    isActive: false,
  },
  {
    id: 9,
    name: "Lucas Silva",
    email: "lucas.silva@example.com",
    age: 33,
    country: "Brazil",
    isActive: true,
  },
  {
    id: 10,
    name: "Sofia Rossi",
    email: "sofia.rossi@example.com",
    age: 26,
    country: "Italy",
    isActive: true,
  },
];

console.log(99);
