export const fruits = [
  "Apple",
  "Banana",
  "Orange",
  "Mango",
  "Pineapple",
  "Strawberry",
  "Blueberry",
  "Grapes",
  "Watermelon",
  "Papaya",
  "Kiwi",
  "Peach",
  "Plum",
  "Cherry",
  "Pomegranate",
  "Guava",
  "Lychee",
  "Coconut",
  "Dragonfruit",
  "Pear",
];

export const fruitsDetail = [
  { name: "Apple", color: "Red", price: 1.2 },
  { name: "Banana", color: "Yellow", price: 0.5 },
  { name: "Orange", color: "Orange", price: 0.8 },
  { name: "Mango", color: "Orange-Yellow", price: 1.5 },
  { name: "Pineapple", color: "Brown-Yellow", price: 2.0 },
  { name: "Strawberry", color: "Red", price: 1.8 },
  { name: "Blueberry", color: "Blue", price: 2.5 },
  { name: "Grapes", color: "Green/Purple", price: 1.6 },
  { name: "Watermelon", color: "Green-Red", price: 3.0 },
  { name: "Papaya", color: "Orange", price: 1.7 },
  { name: "Kiwi", color: "Brown-Green", price: 1.1 },
  { name: "Peach", color: "Pink-Orange", price: 1.3 },
  { name: "Plum", color: "Purple-Red", price: 1.4 },
  { name: "Cherry", color: "Red", price: 2.2 },
  { name: "Pomegranate", color: "Red", price: 2.8 },
  { name: "Guava", color: "Green", price: 1.0 },
  { name: "Lychee", color: "Pink-White", price: 2.0 },
  { name: "Coconut", color: "Brown", price: 2.5 },
  { name: "Dragonfruit", color: "Pink-White", price: 3.2 },
  { name: "Pear", color: "Green-Yellow", price: 1.2 },
];

export const users = [
  {
    id: 1,
    name: "Alice Johnson",
    age: 28,
    email: "alice.johnson@example.com",
    country: "USA",
  },
  {
    id: 2,
    name: "Rahul Mehta",
    age: 32,
    email: "rahul.mehta@example.com",
    country: "India",
  },
  {
    id: 3,
    name: "Sophia Lee",
    age: 24,
    email: "sophia.lee@example.com",
    country: "South Korea",
  },
  {
    id: 4,
    name: "James Smith",
    age: 40,
    email: "james.smith@example.com",
    country: "UK",
  },
  {
    id: 5,
    name: "Maria Garcia",
    age: 29,
    email: "maria.garcia@example.com",
    country: "Spain",
  },
  {
    id: 6,
    name: "Hiroshi Tanaka",
    age: 35,
    email: "hiroshi.tanaka@example.com",
    country: "Japan",
  },
  {
    id: 7,
    name: "Olivia Brown",
    age: 22,
    email: "olivia.brown@example.com",
    country: "Canada",
  },
  {
    id: 8,
    name: "Liam Wilson",
    age: 31,
    email: "liam.wilson@example.com",
    country: "Australia",
  },
  {
    id: 9,
    name: "Zara Ahmed",
    age: 27,
    email: "zara.ahmed@example.com",
    country: "UAE",
  },
  {
    id: 10,
    name: "Daniel Müller",
    age: 33,
    email: "daniel.muller@example.com",
    country: "Germany",
  },
  {
    id: 11,
    name: "Chloe Martin",
    age: 26,
    email: "chloe.martin@example.com",
    country: "France",
  },
  {
    id: 12,
    name: "Ethan Kim",
    age: 30,
    email: "ethan.kim@example.com",
    country: "South Korea",
  },
  {
    id: 13,
    name: "Nina Rossi",
    age: 34,
    email: "nina.rossi@example.com",
    country: "Italy",
  },
  {
    id: 14,
    name: "Lucas Silva",
    age: 28,
    email: "lucas.silva@example.com",
    country: "Brazil",
  },
  {
    id: 15,
    name: "Emma Andersson",
    age: 25,
    email: "emma.andersson@example.com",
    country: "Sweden",
  },
  {
    id: 16,
    name: "Omar Hassan",
    age: 38,
    email: "omar.hassan@example.com",
    country: "Egypt",
  },
  {
    id: 17,
    name: "Isabella Martinez",
    age: 21,
    email: "isabella.martinez@example.com",
    country: "Mexico",
  },
  {
    id: 18,
    name: "Noah Brown",
    age: 29,
    email: "noah.brown@example.com",
    country: "USA",
  },
  {
    id: 19,
    name: "Chen Wei",
    age: 36,
    email: "chen.wei@example.com",
    country: "China",
  },
  {
    id: 20,
    name: "Fatima Khan",
    age: 23,
    email: "fatima.khan@example.com",
    country: "Pakistan",
  },
];
